workflows

diff --git a/.github/workflows/appimage_alpine.yml b/.github/workflows/appimage_alpine.yml
--- a/.github/workflows/appimage_alpine.yml
+++ b/.github/workflows/appimage_alpine.yml
@@ -39,7 +39,7 @@ jobs:
       - name: Build code with static linking
         run: |
           export CC=musl-gcc
-          export LDFLAGS="-static -Wl,-z,relro,-lz"
+         #export LDFLAGS="-static -Wl,-z,relro,-lz"
           make
 
       - name: Prepare AppDir
@@ -61,16 +61,14 @@ jobs:
       - name: Download and prepare appimagetool
         run: |
           wget -O appimagetool-x86_64.AppImage -c https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases/expanded_assets/continuous -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
+          if [ ! -f appimagetool-*.AppImage ]; then
+            echo "appimagetool download failed"; exit 1;
+          fi          
           chmod +x appimagetool-x86_64.AppImage
 
-      - name: Extract appimagetool
+      - name: Use appimagetool with --appimage-extract-and-run
         run: |
-          ./appimagetool-x86_64.AppImage --appimage-extract
-          mv squashfs-root/usr/bin/appimagetool ./appimagetool
-
-      - name: Deploy desktop file
-        run: |
-          ./appimagetool deploy appdir/usr/share/applications/kew.desktop
+          ./appimagetool-x86_64.AppImage --appimage-extract-and-run deploy appdir/usr/share/applications/kew.desktop
 
       - name: Remove unnecessary libraries
         run: |
@@ -81,15 +79,22 @@ jobs:
 
       - name: Create AppImage
         run: |
-          ./appimagetool ./appdir
+          mkdir -p output
+          VERSION=$(./appdir/usr/bin/kew --version | awk -F": " 'FNR==6 {printf $NF}') ./appimagetool-*.AppImage ./appdir -o output
 
-      - name: Rename AppImage and move to output dir
+      - name: Rename AppImage
         run: |
-          mkdir -p musl
-          mv *.AppImage musl/kew
+          mv output/*.AppImage kew
+          chmod +x kew      
 
-      - name: Upload AppImage artifact
-        uses: actions/upload-artifact@v3
+      - name: Release
+        uses: marvinpinto/action-automatic-releases@latest
         with:
-          name: kew-appimage-musl
-          path: musl/kew
+          title: kew appImage (musl systems) 
+          automatic_release_tag: stable
+          prerelease: false
+          draft: true
+          files: |
+            kew
+          repo_token: ${{ secrets.GITHUB_TOKEN }}
+          
diff --git a/.github/workflows/appimage_ubuntu.yml b/.github/workflows/appimage_ubuntu.yml
--- a/.github/workflows/appimage_ubuntu.yml
+++ b/.github/workflows/appimage_ubuntu.yml
@@ -13,15 +13,27 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
-    - name: Download built executable
-      uses: actions/download-artifact@v3
-      with:
-        name: ubuntu-executable-artifact
-        path: ./appdir/usr/bin
+    - name: Install build essentials
+      run: sudo apt-get update && sudo apt-get install -y build-essential
+
+    - name: Install dependencies
+      run: sudo apt install -y ffmpeg libfftw3-dev libopus-dev libopusfile-dev libvorbis-dev libchafa-dev libfreeimage-dev libavformat-dev libstb-dev libnotify-dev wget
+
+    - name: Build code
+      run: |
+        make
+
+    - name: Prepare AppDir
+      run: |
+        mkdir -p appdir/usr/bin
+        mv ./kew appdir/usr/bin/
 
     - name: Download and prepare appimagetool
       run: |
-        wget -c https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases/expanded_assets/continuous -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
+        wget -O appimagetool-x86_64.AppImage -c https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases/expanded_assets/continuous -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
+        if [ ! -f appimagetool-*.AppImage ]; then
+          echo "appimagetool download failed"; exit 1;
+        fi          
         chmod +x appimagetool-*.AppImage
 
     - name: Deploy desktop file
@@ -37,15 +49,21 @@ jobs:
 
     - name: Create AppImage
       run: |
-        ./appimagetool-*.AppImage ./appdir
+        mkdir -p output
+        VERSION=$(./appdir/usr/bin/kew --version | awk -F": " 'FNR==6 {printf $NF}') ./appimagetool-*.AppImage ./appdir -o output
 
-    - name: Rename AppImage and move to output dir
+    - name: Rename AppImage
       run: |
-        mkdir -p glibc
-        mv *.AppImage glibc/kew
+        mv output/*.AppImage kew
+        chmod +x kew        
 
-    - name: Upload AppImage artifact
-      uses: actions/upload-artifact@v3
+    - name: Release
+      uses: marvinpinto/action-automatic-releases@latest
       with:
-        name: kew-appimage-glibc
-        path: glibc/kew
+        title: kew appImage (glibc systems, most systems) 
+        automatic_release_tag: stable
+        prerelease: false
+        draft: true
+        files: |
+          kew
+        repo_token: ${{ secrets.GITHUB_TOKEN }}
